### PR TITLE
PM: Add serial suspension

### PR DESCRIPTION
**Pull request by edwakuwaku**
-LOGUART need to be suspended before entering sleep
-Added suspension logic in serial
TBD: Check for MICOM UART port

### CODE REVIEW

**Comment by amogh-samsung** [comment]
@edwakuwaku I see the hang-up behavior after wake-up after applying this commit as well.
I pulled the latest commit, applied this PR as a patch, built hello_8M config, flashed and booted the board.

The logs stop as described in https://github.com/ziyik/TizenRT/pull/1#issuecomment-1765779336 

I suspected it may be because of connection problems with Windows Virtual Box so I tried on Physical Linux machine, but unfortunately behavior remains same.
I am using 15,00,000 baud rate with 8-N-1 stop bits.

**Comment by amogh-samsung** [comment]
Is the difference in our observations due to difference in board versions, or something else?

**Comment by edwakuwaku** [comment]
It is too difficult to make any conclusion at this point of time, but there is a few experiment that you might want to give it a try.
1) Change another UART JIG to try
2) Erase the flash before downloading the image

**Comment by edwakuwaku** [comment]
Dear @amogh-samsung ,

We have verified with BLE Adv as wakeup interrupt source, it is working fine on our side.
PR: https://github.com/ziyik/TizenRT/pull/3
For this PR, it is a workaround fix for a hardfault if there is any operation being executed at PM_SLEEP state, a hardfault will occur, and it seems to be happening from kernel which the sched module is trying to remove a tcb but somehow ntcb is already NULL at the time being.
Could you help to take a look on our fix? So that we could bring the discussion further.
Attached figure is the hardfault snippet:
image

Next on, we will verify on MICOM UART and update u again.
Thank you~

**Comment by edwakuwaku** [comment]
Dear @amogh-samsung ,

May I know what is the situation on your side? Is the hang issue resolved?

Thank you.

**Comment by edwakuwaku** [comment]
Dear @amogh-samsung ,

I have tested the EVB with using both our own trace tool and tera term, I am still unable to reproduce your situation.
We currently suspect that the problem might be coming from the board, we will try with more other evb and see whether the hang is reproducible.

Thank you.

**Comment by amogh-samsung** [comment]
Hi @edwakuwaku 
Sorry for the delayed response and thanks for the update.
I will try out a few more scenarios and get back to you after some time please.
As of now I have tried with 2 different EVBxJIG pairs and on different machines.

Hence, I want to ask you again, maybe our boards are different versions or something like that?

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

I have reproduced your situation with another EVB, we can eliminate the possibility of UART JIG as problem source.
I tried 3 EVB in total, 2 is samsung evb, and one is our own evb, and both the samsung evb we received is the same batch, but only one is working, and our own evb is also hanging.
This situation is very unusual, maybe I should investigate on the hardware part of it.
I will update you again if there is any progress.

Thank you.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Could you share with us the download time taken for downloading the images to the EVB?

Thank you.

**Comment by amogh-samsung** [comment]
> Hi @amogh-samsung ,
> 
> Could you share with us the download time taken for downloading the images to the EVB?
> 
> Thank you.

Approximate download times
km4_boot_all -> 5 secs
kernel trpk -> 45 secs
bootparam -> 1 sec

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Thank you for the information. We have conducted some long run for power save throughout the weekend, I will share the logs with you via email. For the hang issue on other boards, we are still investigating and trying to come out with some solution to compromise.

Thank you.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

I think as the file size is too big (~41Mb), it has been rejected by your internal system. Please let me know how should I share the file with you if you need it.

Thank you!

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

There is some fix that might be able to resolve the hang issue you are facing. Could you pull to the latest commit and try it out?
We have tried some other boards, some of the boards which is failing previously, seems to be working fine now. But there is still some EVB facing the same issue. I have tried on 3 8th gen EVB and 1 4th gen EVB, 1 RTK EVB.
Results: 
1 8th gen EVB,  1 4th gen EVB and 1 RTK EVB will not hang
2 8th gen EVB faced hang

Thank you~

**Comment by amogh-samsung** [comment]
> Hi @amogh-samsung ,
> 
> I think as the file size is too big (~41Mb), it has been rejected by your internal system. Please let me know how should I share the file with you if you need it.
> 
> Thank you!

You can share a google drive link with me for viewing

**Comment by amogh-samsung** [comment]
> Hi @amogh-samsung ,
> 
> There is some fix that might be able to resolve the hang issue you are facing. Could you pull to the latest commit and try it out? We have tried some other boards, some of the boards which is failing previously, seems to be working fine now. But there is still some EVB facing the same issue. I have tried on 3 8th gen EVB and 1 4th gen EVB, 1 RTK EVB. Results: 1 8th gen EVB, 1 4th gen EVB and 1 RTK EVB will not hang 2 8th gen EVB faced hang
> 
> Thank you~

@edwakuwaku Sorry for being the bearer of bad news, I tried with 2 boards, both of them still hang up after 
`INFO:    ARM GICv2 driver initialized`
HEAD @ `4efc0f42b5c9829fe5c2d502a27a330dabd5435b`

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Here is the link: https://drive.google.com/file/d/1Va7yBKLQYPV1lO9ZzlDZx1Ury1IFC6C7/view?usp=drive_link



> > Hi @amogh-samsung ,
> > There is some fix that might be able to resolve the hang issue you are facing. Could you pull to the latest commit and try it out? We have tried some other boards, some of the boards which is failing previously, seems to be working fine now. But there is still some EVB facing the same issue. I have tried on 3 8th gen EVB and 1 4th gen EVB, 1 RTK EVB. Results: 1 8th gen EVB, 1 4th gen EVB and 1 RTK EVB will not hang 2 8th gen EVB faced hang
> > Thank you~
> 
> @edwakuwaku Sorry for being the bearer of bad news, I tried with 2 boards, both of them still hang up after `INFO: ARM GICv2 driver initialized` HEAD @ `4efc0f42b5c9829fe5c2d502a27a330dabd5435b`

Sorry for the hang issue, we are still trying to conduct more test on different boards, this situation is a really weird case and I hope for the understanding from you and your team. We are still trying to figure out some solutions to compromise with such cases, at least to help you move on further to verify the power save feature.

Thank you very much!

**Comment by amogh-samsung** [comment]
> Hi @amogh-samsung ,
> 
> Here is the link: https://drive.google.com/file/d/1Va7yBKLQYPV1lO9ZzlDZx1Ury1IFC6C7/view?usp=drive_link
> 
> > > Hi @amogh-samsung ,
> > > There is some fix that might be able to resolve the hang issue you are facing. Could you pull to the latest commit and try it out? We have tried some other boards, some of the boards which is failing previously, seems to be working fine now. But there is still some EVB facing the same issue. I have tried on 3 8th gen EVB and 1 4th gen EVB, 1 RTK EVB. Results: 1 8th gen EVB, 1 4th gen EVB and 1 RTK EVB will not hang 2 8th gen EVB faced hang
> > > Thank you~
> > 
> > 
> > @edwakuwaku Sorry for being the bearer of bad news, I tried with 2 boards, both of them still hang up after `INFO: ARM GICv2 driver initialized` HEAD @ `4efc0f42b5c9829fe5c2d502a27a330dabd5435b`
> 
> Sorry for the hang issue, we are still trying to conduct more test on different boards, this situation is a really weird case and I hope for the understanding from you and your team. We are still trying to figure out some solutions to compromise with such cases, at least to help you move on further to verify the power save feature.
> 
> Thank you very much!

@edwakuwaku We understand and appreciate your efforts, please keep us updated :)

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Here is some quick updates. Despite of the hang issues on several boards, we have verified with MICOM UART as wakeup interrupt source, using EVB which is not facing hang issue.

In conclusion, 3 types of wakeup source which are timer, uart, and ble adv has been verified from our side. I will keep you posted with the hang issue.

Thank you.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

There is a new commit which seems to fix the hang issue, can you checkout this commit and try? 
My working repo: https://github.com/edwakuwaku/SamsungTizen/tree/power_save_branch
https://github.com/Samsung/TizenRT/commit/306ad982f9023d076e0cec3edd3b441378dc9352
This can fix the hang issue I am facing on some of the evb on my side, hope it could fix yours too.
Actually in assembly layer, the system has already faced crash, but as in we just come back from sleep mode, it is still in the phase for restoring the registers, so it will just hang instead of crash and dump the systems logs, which made it more difficult to locate the rootcause. I will check more on why it is resulting crash on some of the evbs.

Thank you~

**Comment by amogh-samsung** [comment]
> Hi @amogh-samsung ,
> 
> There is a new commit which seems to fix the hang issue, can you checkout this commit and try? My working repo: https://github.com/edwakuwaku/SamsungTizen/tree/power_save_branch [Samsung@306ad98](https://github.com/Samsung/TizenRT/commit/306ad982f9023d076e0cec3edd3b441378dc9352) This can fix the hang issue I am facing on some of the evb on my side, hope it could fix yours too. Actually in assembly layer, the system has already faced crash, but as in we just come back from sleep mode, it is still in the phase for restoring the registers, so it will just hang instead of crash and dump the systems logs, which made it more difficult to locate the rootcause. I will check more on why it is resulting crash on some of the evbs.
> 
> Thank you~

Thankyou @edwakuwaku for figuring this out. With the above mentioned change, I do not see the board hang like before.

However, once in many cycles, I see the board hang up here "[up_idlepm] - 165, state = 3"
i.e. idle.c tries to change to sleep state, but the board side changes did not happen.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

That scenario is common, as I have set the interrupt count to run a fixed amount of sleep/wake cycle. You may check it from amebasmart_idle.c~ Other than the hang, the main point is too confirmed that the tash is also working fine on your side~ When the sleep/wake cycle has stopped as per your observation, you may try to input any command, it will go back to normal, and do state transition again.

Additionally, the SCTLR reg bit which will be written in the restore phase, actually it has been written once in the BL32 during warm boot phase, when the core is awaken by interrupt source. So, it might be the point that cause the crash, but it is also hard to explain why this scenario is not happening in all EVBs.

Thank you~

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Can I have a quick update of the status on your side?

Here is some status update from our side.
Recently when we are trying to add in some other driver modules (such as wifi) into the whole system (pushing forward to mimic actual scenarios). We found that the workaround we provided will cause some memory misalignment issue happening, resulting system crash. So, we are trying to resolve this issue at the highest priority, as in the later stage, we will expect a more complicated scenario coming in during the real application. 
Additionally, this part is closely related to system architecture, which in our case is (cortex-A32), and I am checking back to the armv7-A arch codes from Nuttx, which some of the assembly operation regarding system registers has to be revised accordingly to be compatible with A32 core.
Please share with us if you have any idea on this.

Thank you~

**Comment by amogh-samsung** [comment]
Hello @edwakuwaku , I have been on leave for a couple of days due to sickness.
No new updates from my side. As you mentioned and we observed, the PM module is working fine after you suggested some changes in the assembly code.
Please let me know if you want me to look into something specific.

**Comment by edwakuwaku** [comment]
Hello @amogh-samsung ,

I hope you have recovered well through the past few days.
For this crash issue due to the assembly operation, I am checking through the armv7-A arch codes, although the A32 chip can backward compatible with v7-A family. But down to system register layer, we still have to follow cortex-A32 specification.
For the time being, I heard that Samsung application layer will also register to the PM domain. So, I will prepare a guide for that, and also the PM logic workflow together in a PPT. I will share a problem we have found and the workaround fix, that problem seems to be related to PM module from Nuttx. The rough description for the problem is that when the state drop to PM_STANDBY, PM_SLEEP, if we are going to execute some operations at those states, it might cause a crash. And after checking, it seems like there is an assert happening from the tcb part. The workaround is to create a task to execute the required operation, to avoid the tcb to be empty, which it was trying to clean something from empty block.
I will provide the findings together, I hope you could help to check on that matter for the time being if you have the time to do so~

Thank you.

Best Regards,
Edward.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

I have shared the PPT in the email loop, but after considering, I didn't share the crash problem happening as mentioned above. It is because it might not be that high priority to check that since we have stable workaround for that at the moment. But, if Samsung App face such condition when undergoing some operation during PM states (in the callback API), we should put some effort to check this problem by then.

Thank you~

**Comment by amogh-samsung** [comment]
Hi @edwakuwaku 

One point of information. It may not be suitable to start new operations from the idle_thread as calling blocking functions within the operations from here can lead to crashes (If current thread is blocked, context cannot be switched to any other thread since current thread i.e. idle is the only thread). This might be why you observed a crash.

Also, I would like to understand what exactly you refer to by Samsung App (maybe which layer exactly, wifi/ble manager, or PM module control flow in idle.c?). I understand that all the layers above yours could be App for you, and there has been discussion about Samsung App being able to control SLEEP behavior of board.

**Comment by edwakuwaku** [comment]
Hello @amogh-samsung ,

This crash is not only observed in the idle loop, when there is a state change ongoing, the module will go to check through all the registered callback structures, and if there is operation needed to be executed, it might also face crash. Do you mean that anything starting from the idle loop will have the possibility to face such condition (as there are included in the idle loop thread)?
(ie. pm_changestate.c -> rtk_bt_power_control.c)

Basically the codes under path os/arch/arm/amebasmart should be controlled by us, and also os/board/rtl8730e/src/component, remaining level other than these few would be out of our scope. Definitely the usage of PM_RELAX, PM_STAY, PM_ACTIVITY should be utilized by the Application level to control the PM behavior. The Samsung App are referring to the upper layer applications (perhaps for the apps in the loadable_apps config?), for the wifi/ble/serial, these can be controlled at driver layer, so it might not be necessary to change anything from you side.

**Comment by amogh-samsung** [comment]
Hi @edwakuwaku 
Thankyou for the update

Could you share the crash logs and an explanation of the crash scenario via mail please? If we have any insights, we will share with you.

I understand the second point above, thankyou.

**Comment by edwakuwaku** [comment]
> Hi @amogh-samsung ,
> 
> Here is some quick updates. Despite of the hang issues on several boards, we have verified with MICOM UART as wakeup interrupt source, using EVB which is not facing hang issue.
> 
> In conclusion, 3 types of wakeup source which are timer, uart, and ble adv has been verified from our side. I will keep you posted with the hang issue.
> 
> Thank you.

Hi @amogh-samsung ,

Sorry for informing, we found that there is some issue when verifying using PA4, PA5 for MICOM UART as wakeup source, we are checking it at the moment, and will keep you posted. I apologize again for sharing this information.

Thank you.

**Comment by amogh-samsung** [comment]
Hi @edwakuwaku, thankyou for sharing the information.
Please keep us posted with any further updates.

**Comment by amogh-samsung** [comment]
> Hello @amogh-samsung ,
> 
> This crash is not only observed in the idle loop, when there is a state change ongoing, the module will go to check through all the registered callback structures, and if there is operation needed to be executed, it might also face crash. Do you mean that anything starting from the idle loop will have the possibility to face such condition (as there are included in the idle loop thread)? (ie. pm_changestate.c -> rtk_bt_power_control.c)
> 
> Basically the codes under path os/arch/arm/amebasmart should be controlled by us, and also os/board/rtl8730e/src/component, remaining level other than these few would be out of our scope. Definitely the usage of PM_RELAX, PM_STAY, PM_ACTIVITY should be utilized by the Application level to control the PM behavior. The Samsung App are referring to the upper layer applications (perhaps for the apps in the loadable_apps config?), for the wifi/ble/serial, these can be controlled at driver layer, so it might not be necessary to change anything from you side.

Hi @edwakuwaku , regarding the first point above.
"Do you mean that anything starting from the idle loop will have the possibility to face such condition (as there are included in the idle loop thread)"
Sorry for the delayed response, but basically, yes.
If whatever is started from here, leads to a function call that blocks this task itself, then the scheduler will try to pre-empt the current task and bring in a new one. However, since this is the idle thread and there is no other task to bring in, we face a problematic situation, as is checked here ( https://github.com/Samsung/TizenRT/blob/4cced9a8944514cac4c28a2aab2717138b1e474b/os/kernel/sched/sched_removereadytorun.c#L120 )

So when you create a different task, that task can get block and pre-empted and idle task can come back in, and hence it works fine.

**Comment by edwakuwaku** [comment]
Dear @amogh-samsung ,

Thank you for your explanation, I have the similar observation as you, that's why I come out with this solution to mitigate such condition.
1) Could I understand it as this current workaround is feasible for such condition?
1a) If yes, does it means in the future if there is any related crash, we should follow this fix?
1b) If no, do your side have any idea on how can we overcome this condition? (We could discuss more during the meeting on Friday)~

Thank you!!

**Comment by amogh-samsung** [comment]
Hi @edwakuwaku 
It would be preferred to find out the exact source/reason of the context switch, i.e. the blocking function if any that is causing the idle task to get switched out, hence leaving us with a crash.
Then, if possible, we should replace it with a non-blocking function.

The current implementation, is yes a workaround. It may be feasible here, we should check a bit more and conclude (I mean it may be the way to solve this problem case here).
However it would NOT be correct to say that this should be the method to always follow in the future in such a situation. We will try to get you an update by Friday during our meeting as you mentioned.

**Comment by edwakuwaku** [comment]
Hello @amogh-samsung ,

Yes, I definitely agree with your points. Additionally, I heard from Mr.Chang that the PR for SMP armv7-A will be merged to master soon, so it will be good if you could provide a clear usage of application to integrate with the PM module, so I can provide a wrapper api for your operation, and you could proceed to test on some simple application. How do you think?

Thank you~

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

The crash issue has been resolved in this commit, please take a look for your reference~
https://github.com/Samsung/TizenRT/commit/141d206b0818621e259c98d5284f172efc5b88d0

Besides, we will move on to finalize and submit for PR, by the time, you may also checkout the PR and verify the wakeup source requested. Additionally, as discussed in the last meeting, we would like to ask if there is any input from your side regarding the timer interrupt usage? 

Thank you~

**Comment by amogh-samsung** [comment]
@edwakuwaku 
Thankyou for the update. Can I pull the power_save branch now for the latest changes and test?
I will share details about the PM state control from the APP side soon. pm_stay and pm_relax should be able to do most of the work as discussed before.
However, in loadable apps environment, apps may not have access to these functions directly. I will elaborate more on these in a separate communication.

**Comment by edwakuwaku** [comment]
Hi @amogh-samsung ,

Yes, you may pull to the latest commit and test, which is under my repo.
Understood, I will checkout the PR from you.
Ok, I think we could figure out a way round to fulfil your requirement.

Thanks~

**Pull request merged**
